newshub/Controllers/FavoriteController.cs
using Microsoft.AspNetCore.Mvc;

namespace newshub.Controllers
{

    public class FavoriteController : Controller
    {
        private const string SessionKey = "FavoriteArticles";

        [HttpPost]
        public IActionResult AddToFavorites(
            string articleTitle,
            string articleImage,
            string articleDescription,
            string articleUrl,
            string articleChannel
        )

        {
            var userId = HttpContext.Session.GetString("userID");
            if (string.IsNullOrEmpty(userId))
            {
                return Json(new { success = false, message = "Please login first." });
            }



            var favorites = HttpContext.Session.GetObject<List<string>>(SessionKey) ?? new List<string>();

           
            if (!favorites.Contains(articleTitle))
            {
                favorites.Add(articleTitle);
                favorites.Add(articleImage);
                favorites.Add(articleDescription);
                favorites.Add(articleUrl);
                favorites.Add(articleChannel);

                HttpContext.Session.SetObject(SessionKey, favorites);
            }

            return Json(new { success = true });
        }

        public IActionResult Index()
        {
            var favorites = HttpContext.Session.GetObject<List<string>>(SessionKey) ?? new List<string>();
            return View(favorites);
        }
    }
}

//using Microsoft.AspNetCore.Authorization;
//using Microsoft.AspNetCore.Identity;
//using Microsoft.AspNetCore.Mvc;
//using System.Threading.Tasks;
//using newshub.Models;
//using System.Linq;
//using Microsoft.EntityFrameworkCore;
//using newshub.Data;

//namespace newshub.Controllers
//{
//    [Authorize]
//    public class FavoriteController : Controller
//    {
//        private readonly UserManager<Register> _userManager;
//        private readonly UserdbContext db;

//        public FavoriteController(UserManager<Register> userManager, UserdbContext db)
//        {
//            _userManager = userManager;
//            this.db = db;
//        }

//        [HttpPost]
//        public async Task<IActionResult> AddToFavorites(string articleTitle)
//        {
//            var user = await _userManager.GetUserAsync(User);
//            if (user != null)
//            {
//                // Associate the favorite article with the current user
//                var favorite = new Favorite { UserId = user.userID, ArticleTitle = articleTitle };
//                // Add code to save the favorite to the database
//                db.Favoriteuser.Add(favorite);
//                await db.SaveChangesAsync();
//                return Json(new { success = true });
//            }
//            return Json(new { success = false });
//        }

//        public async Task<IActionResult> Index()
//        {
//            var user = await _userManager.GetUserAsync(User);
//            if (user != null)
//            {
//                // Retrieve favorite articles associated with the current user
//                var favorites = await db.Favoriteuser.Where(f => f.UserId == user.userID).ToListAsync();
//                return View(favorites);
//            }
//            return View(new List<Favorite>());
//        }
//    }
//}

newshub/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@{
    
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Style.css" />
</head>
<body class="m-0 p-0" style="background-color:#212529; overflow-y: auto;">
    <header>
        <div class="container-fluid m-0 p-0">
            <div>

                <nav class="navbar navbar-expand-lg navbar-dark fixed-top " style="background-color:rgb(41, 47, 51); padding: 20px; font-size: 18px;">
                     <div class="container-fluid">
                           <a class="navbar-brand text-blue">
                                <img src="~/image/logoImage.png" alt="Logo" style="width:45px"/>NEWS Hub
                           </a>


                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="Home" asp-route-category="home">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="Home" asp-route-category="general">General</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="Home" asp-route-category="business">Business</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="Home" asp-route-category="sports">Sports</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="Home" asp-route-category="science">Science</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="Home" asp-route-category="health">Health</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="Home" asp-route-category="entertainment">Entertainment</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="Home" asp-route-category="technology">Technology</a>
                                </li> 
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="Index" asp-controller="Favorite">Favorite</a>
                                </li> 
                            </ul>
                            <form class="d-flex" method="get" id="searchForm">
                                <input class="form-control me-2" type="text" id="newsQuery" name="query" placeholder="Enter your search query">
                                <button class="btn btn-primary" type="button" onclick="searchNews()" style="margin-right:10px">Search</button>
                                @if (!string.IsNullOrEmpty(Context.Session.GetString("uname")))
                                {
                                    <a class="nav-link" style="color:aliceblue; font-size:large; font-style:oblique"><b>@(Context.Session.GetString("uname"))</b></a>
                                    <a class="nav-link" asp-action="Logout" asp-controller="Home">Logout</a>
                                }
                                else
                                {
                                    <a class="btn btn-outline-primary" style="margin-right:10px" asp-action="Register" asp-controller="Home">Register</a>
                                    <a class="btn btn-outline-primary" asp-action="Login" asp-controller="Home">Login</a>
                                }
                            </form>
                        </div>
               
                    </div>
                </nav>
            </div>
        </div>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted" style="background-color:rgb(41, 47, 51);">
        
            &copy; @DateTime.Now.Year - NEWS Hub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        
    </footer>
  
   

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
  
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        function searchNews() {
            var query = document.getElementById("newsQuery").value.trim();
            if (query !== "") {
                var encodedQuery = encodeURIComponent(query);
                var url = `/News/SearchNews?query=${encodedQuery}`;
                window.location.href = url;
            } else {
                alert("Please enter a search query.");
            }
        }

        document.getElementById("searchForm").addEventListener("submit", function (event) {
            event.preventDefault();
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

newshub/Views/Shared/_LayoutAdmin.cshtml
@{
    var aname = Context.Session.GetString("name");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
   
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/admin.css" />
    <link rel="stylesheet" href="~/css/all.min.css" />
    <link rel="stylesheet" href="~/css/media.css" />


</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">


            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a asp-action="userShow" asp-controller="Admin">Users</a>
                    </li>

                </ul>
                <div style="align-items:flex-end">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item fa-align-right">
                            <a style="font-family:'Bell MT'">@aname</a>
                        </li>
                        <li class="nav-item fa-align-right">
                            <a asp-action="Logout" asp-controller="Home">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
         
        </nav>
    </header>
    

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  
    <footer>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    </footer>

</body>
</html>